#
# 

#
#	Makefile のプロセッサ依存部（Blackfin用）
#

#
#  ターゲットアーキテクチャの定義
#
TARGET = bfin-elf

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)
COPTS := $(COPTS) -Wall -g -O2  
CDEFS := $(CDEFS) -D __ADSPLPBLACKFIN__ -DLABEL_ASM

#
#  カーネルに関する定義
#    cpu_mmr.oは、gdbのためのcore mmr用デバッグ・シンボル。
#
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) cpu_support.o
KERNEL_COBJS := $(KERNEL_COBJS) cpu_config.o cpu_defs.o cpu_mmr.o

#
#  スタートアップモジュールに関する定義
#
START_OBJS = start.o

$(START_OBJS): %.o: %.S
	$(CC) -c $(CFLAGS) $(KERNEL_CFLAGS) $<

$(START_OBJS:.o=.d): %.d: %.S
	@$(PERL) $(SRCDIR)/utils/makedep -C $(CC) \
		-O "$(CFLAGS) $(KERNEL_CFLAGS)" $< >> Makefile.depend
